// Canonical menu items for Sherazi POS (mirrors frontend mockData; no local ids).

/** @type {Array<{name:string,price:number,halfPrice?:number,category:string,description:string,available:boolean,perishable:boolean,kitchenRequired?:boolean}>} */
const MENU_ITEMS = [
  { name: "Shinwari Lamb Namkeen White Karahi", price: 3400, halfPrice: 1700, category: "Shinwari", description: "Traditional white shinwari lamb karahi", available: true, perishable: true, kitchenRequired: true },
  { name: "Shinwari Lamb Namkeen Karahi", price: 3400, halfPrice: 1700, category: "Shinwari", description: "Classic namkeen shinwari lamb karahi", available: true, perishable: true, kitchenRequired: true },
  { name: "Shinwari Lamb Sulamani Karahi", price: 3400, halfPrice: 1700, category: "Shinwari", description: "Sulamani style lamb karahi", available: true, perishable: true, kitchenRequired: true },
  { name: "Shinwari Lamb Do Payaza Karahi", price: 3400, halfPrice: 1700, category: "Shinwari", description: "Lamb karahi with onions", available: true, perishable: true, kitchenRequired: true },
  { name: "Dum Pukht", price: 3400, halfPrice: 1700, category: "Shinwari", description: "Slow-cooked lamb dum pukht", available: true, perishable: true, kitchenRequired: true },
  { name: "Roash", price: 1200, category: "Shinwari", description: "Traditional roash", available: true, perishable: true, kitchenRequired: true },
  { name: "Lamb Namkeen Tikka", price: 3400, halfPrice: 1700, category: "Shinwari", description: "Shinwari BBQ lamb tikka", available: true, perishable: true, kitchenRequired: true },
  { name: "Lamb Patta Tikka 8PC", price: 1000, category: "Shinwari", description: "8 pieces of lamb patta tikka", available: true, perishable: true, kitchenRequired: true },
  { name: "Ranjha Gosht", price: 3400, halfPrice: 1700, category: "Shinwari", description: "Ranjha style gosht", available: true, perishable: true, kitchenRequired: true },
  { name: "Badmi Chanp", price: 3400, halfPrice: 1700, category: "Shinwari", description: "Tender badmi chanp", available: true, perishable: true, kitchenRequired: true },
  { name: "Kabli Pulao", price: 1200, category: "Shinwari", description: "Traditional Kabli pulao", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Boti with Bone 12PC", price: 950, category: "BBQ", description: "12 pieces of chicken boti", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Namkeen Boti with Bone 12PC", price: 950, category: "BBQ", description: "12 pieces namkeen boti", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Achari Boti with Bone 12PC", price: 950, category: "BBQ", description: "12 pieces achari boti", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Kabab 4PC", price: 900, category: "BBQ", description: "4 pieces chicken kabab", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Reshmi Kabab 4PC", price: 1100, category: "BBQ", description: "4 pieces reshmi kabab", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Cheese Kabab 4PC", price: 1100, category: "BBQ", description: "4 pieces cheese kabab", available: true, perishable: true, kitchenRequired: true },
  { name: "Beef Kabab 4PC", price: 1000, category: "BBQ", description: "4 pieces beef kabab", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken/Beef Gola Kabab 6PC", price: 900, category: "BBQ", description: "6 pieces gola kabab", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken/Beef Lebnani Kabab 4PC", price: 1000, category: "BBQ", description: "4 pieces lebnani kabab", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Malai Boti (Boneless) 10PC", price: 1000, category: "BBQ", description: "10 pieces boneless malai boti", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Turkish Boti (Boneless) 10PC", price: 1000, category: "BBQ", description: "10 pieces boneless turkish boti", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Cheese Boti (Boneless) 10PC", price: 1150, category: "BBQ", description: "10 pieces boneless cheese boti", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Shish Taouk (Boneless)", price: 1100, category: "BBQ", description: "Boneless shish taouk", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Angara Whole Chicken", price: 1500, category: "BBQ", description: "Whole angara chicken", available: true, perishable: true, kitchenRequired: true },
  { name: "Fish Tikka 10PC", price: 1700, category: "BBQ", description: "10 pieces fish tikka", available: true, perishable: true, kitchenRequired: true },
  { name: "Rahu Fish (Per KG)", price: 1700, category: "BBQ", description: "Fresh Rahu fish per KG", available: true, perishable: true, kitchenRequired: true },
  { name: "Rahu Fish (Half KG)", price: 900, category: "BBQ", description: "Fresh Rahu fish half KG", available: true, perishable: true, kitchenRequired: true },
  { name: "Mutton Makhni Karahi", price: 4100, halfPrice: 2100, category: "Karahi", description: "Creamy makhni mutton karahi", available: true, perishable: true, kitchenRequired: true },
  { name: "Mutton Karahi", price: 4000, halfPrice: 2100, category: "Karahi", description: "Classic mutton karahi", available: true, perishable: true, kitchenRequired: true },
  { name: "Mutton White Karahi", price: 4100, halfPrice: 2100, category: "Karahi", description: "White mutton karahi", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Karahi Special", price: 2100, halfPrice: 1100, category: "Karahi", description: "Special chicken karahi", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Makhni Karahi", price: 2100, halfPrice: 1100, category: "Karahi", description: "Creamy makhni chicken karahi", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken White Karahi", price: 2100, halfPrice: 1100, category: "Karahi", description: "White chicken karahi", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Green Karahi", price: 2100, halfPrice: 1100, category: "Karahi", description: "Green masala chicken karahi", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Karahi", price: 2000, halfPrice: 1100, category: "Karahi", description: "Traditional chicken karahi", available: true, perishable: true, kitchenRequired: true },
  { name: "Special Chicken Handi", price: 2000, category: "Handi", description: "Chef special chicken handi", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Makhni Handi", price: 2000, category: "Handi", description: "Creamy makhni handi", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Achari Handi", price: 2000, category: "Handi", description: "Achari flavored handi", available: true, perishable: true, kitchenRequired: true },
  { name: "Ginger Handi", price: 1950, category: "Handi", description: "Ginger infused handi", available: true, perishable: true, kitchenRequired: true },
  { name: "Jelfrezi Handi", price: 1950, category: "Handi", description: "Spicy jelfrezi handi", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken White Handi", price: 2000, category: "Handi", description: "White chicken handi", available: true, perishable: true, kitchenRequired: true },
  { name: "Hyderabadi Handi", price: 2000, category: "Handi", description: "Hyderabadi style handi", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Chili Dry", price: 1400, category: "Chinese", description: "Dry chili chicken", available: true, perishable: true, kitchenRequired: true },
  { name: "Kung Pao Chicken", price: 1400, category: "Chinese", description: "Spicy kung pao chicken with peanuts", available: true, perishable: true, kitchenRequired: true },
  { name: "Kung Pao Fish", price: 1700, category: "Chinese", description: "Kung pao style fish", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Black Pepper", price: 1400, category: "Chinese", description: "Black pepper chicken", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Manchurian", price: 1400, category: "Chinese", description: "Chicken manchurian", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Almond", price: 1400, category: "Chinese", description: "Almond chicken", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Schezwan", price: 1400, category: "Chinese", description: "Schezwan chicken", available: true, perishable: true, kitchenRequired: true },
  { name: "Sweet & Sour Fish", price: 1700, category: "Chinese", description: "Sweet and sour fish", available: true, perishable: true, kitchenRequired: true },
  { name: "Fish Chili Dry", price: 1700, category: "Chinese", description: "Dry chili fish", available: true, perishable: true, kitchenRequired: true },
  { name: "Shiraz Restaurant Special Rice", price: 1050, category: "Rice", description: "Shiraz Restaurant signature special rice", available: true, perishable: true, kitchenRequired: true },
  { name: "Masala Rice", price: 900, category: "Rice", description: "Spiced masala rice", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Fried Rice", price: 900, category: "Rice", description: "Wok-fried rice with chicken", available: true, perishable: true, kitchenRequired: true },
  { name: "Egg Fried Rice", price: 800, category: "Rice", description: "Classic egg fried rice", available: true, perishable: true, kitchenRequired: true },
  { name: "Beef Chili Rice", price: 900, category: "Rice", description: "Spicy beef chili rice", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Chili Rice", price: 900, category: "Rice", description: "Spicy chicken chili rice", available: true, perishable: true, kitchenRequired: true },
  { name: "Vegetable Rice", price: 850, category: "Rice", description: "Mixed vegetable fried rice", available: true, perishable: true, kitchenRequired: true },
  { name: "Steam Rice", price: 600, category: "Rice", description: "Plain steamed rice", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Pulao", price: 600, category: "Rice", description: "Traditional chicken pulao", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Pulao Kabab", price: 750, category: "Rice", description: "Chicken pulao with kabab", available: true, perishable: true, kitchenRequired: true },
  { name: "Pulao Kabab", price: 450, category: "Rice", description: "Pulao with kabab", available: true, perishable: true, kitchenRequired: true },
  { name: "Pulao", price: 400, category: "Rice", description: "Plain pulao", available: true, perishable: true, kitchenRequired: true },
  { name: "Shami Kabab Special", price: 80, category: "Rice", description: "Special shami kabab", available: true, perishable: true, kitchenRequired: true },
  { name: "Shiraz Restaurant Special Chowmein", price: 1300, category: "Noodles", description: "Shiraz Restaurant special chowmein", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Chowmein", price: 1200, category: "Noodles", description: "Chicken chowmein noodles", available: true, perishable: true, kitchenRequired: true },
  { name: "Beef Chowmein", price: 1200, category: "Noodles", description: "Beef chowmein noodles", available: true, perishable: true, kitchenRequired: true },
  { name: "Vegetable Chowmein", price: 1000, category: "Noodles", description: "Vegetable chowmein noodles", available: true, perishable: true, kitchenRequired: true },
  { name: "Shiraz Restaurant Special Lemon Chicken", price: 1100, category: "Appetizers", description: "Signature lemon chicken", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Honey Wings 8PC", price: 850, category: "Appetizers", description: "8 pieces honey glazed wings", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Fried Wings 8PC", price: 700, category: "Appetizers", description: "8 pieces crispy fried wings", available: true, perishable: true, kitchenRequired: true },
  { name: "Fish Crackers", price: 400, category: "Appetizers", description: "Crispy fish crackers", available: true, perishable: false, kitchenRequired: true },
  { name: "French Fries", price: 300, category: "Appetizers", description: "Golden french fries", available: true, perishable: true, kitchenRequired: true },
  { name: "Shiraz Restaurant Special Soup (Family)", price: 1300, category: "Soups", description: "Family size special soup", available: true, perishable: true, kitchenRequired: true },
  { name: "Shiraz Restaurant Special Soup (Single)", price: 400, category: "Soups", description: "Single serving special soup", available: true, perishable: true, kitchenRequired: true },
  { name: "Hot & Sour Soup (Family)", price: 1150, category: "Soups", description: "Family size hot & sour soup", available: true, perishable: true, kitchenRequired: true },
  { name: "Hot & Sour Soup (Single)", price: 400, category: "Soups", description: "Single hot & sour soup", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Corn Soup (Family)", price: 1100, category: "Soups", description: "Family size chicken corn soup", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Corn Soup (Single)", price: 400, category: "Soups", description: "Single chicken corn soup", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Vegetable Soup (Family)", price: 1050, category: "Soups", description: "Family size vegetable soup", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Vegetable Soup (Single)", price: 400, category: "Soups", description: "Single vegetable soup", available: true, perishable: true, kitchenRequired: true },
  { name: "Fish & Chips", price: 1500, category: "Sea Food", description: "Battered fish with chips", available: true, perishable: true, kitchenRequired: true },
  { name: "Finger Fish", price: 1400, category: "Sea Food", description: "Crispy finger fish", available: true, perishable: true, kitchenRequired: true },
  { name: "Dhaka Fish", price: 1400, category: "Sea Food", description: "Dhaka style fish", available: true, perishable: true, kitchenRequired: true },
  { name: "Mutton Leg Roast", price: 3800, category: "Steam", description: "Slow roasted mutton leg", available: true, perishable: true, kitchenRequired: true },
  { name: "Full Chicken Roast", price: 1500, category: "Steam", description: "Whole roasted chicken", available: true, perishable: true, kitchenRequired: true },
  { name: "Half Chicken Roast", price: 800, category: "Steam", description: "Half roasted chicken", available: true, perishable: true, kitchenRequired: true },
  { name: "Club Sandwich", price: 700, category: "Sandwiches", description: "Classic club sandwich", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Sandwich", price: 600, category: "Sandwiches", description: "Grilled chicken sandwich", available: true, perishable: true, kitchenRequired: true },
  { name: "Russian Salad", price: 600, category: "Salads", description: "Creamy Russian salad", available: true, perishable: true, kitchenRequired: true },
  { name: "Kachumber Salad", price: 300, category: "Salads", description: "Fresh kachumber salad", available: true, perishable: true, kitchenRequired: true },
  { name: "Fresh Green Salad", price: 150, category: "Salads", description: "Fresh green salad", available: true, perishable: true, kitchenRequired: true },
  { name: "Raita / Mint Sauce", price: 150, category: "Salads", description: "Yogurt raita or mint sauce", available: true, perishable: true, kitchenRequired: true },
  { name: "Mutton Qorma", price: 850, category: "Regular Items", description: "Traditional mutton qorma", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Qorma", price: 370, category: "Regular Items", description: "Chicken qorma curry", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Qeema", price: 450, category: "Regular Items", description: "Minced chicken qeema", available: true, perishable: true, kitchenRequired: true },
  { name: "Beef Qeema", price: 450, category: "Regular Items", description: "Minced beef qeema", available: true, perishable: true, kitchenRequired: true },
  { name: "Shahi Daal", price: 370, category: "Regular Items", description: "Creamy shahi daal", available: true, perishable: true, kitchenRequired: true },
  { name: "Daal Mash", price: 330, category: "Regular Items", description: "Daal mash", available: true, perishable: true, kitchenRequired: true },
  { name: "Daal Chana", price: 300, category: "Regular Items", description: "Daal chana", available: true, perishable: true, kitchenRequired: true },
  { name: "Mix Vegetable", price: 300, category: "Regular Items", description: "Mixed vegetable curry", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Piece", price: 170, category: "Regular Items", description: "Single chicken piece", available: true, perishable: true, kitchenRequired: true },
  { name: "Special Cheese Naan", price: 400, category: "Tandoor", description: "Stuffed cheese naan", available: true, perishable: true, kitchenRequired: true },
  { name: "Roghni Naan", price: 90, category: "Tandoor", description: "Buttery roghni naan", available: true, perishable: true, kitchenRequired: true },
  { name: "Garlic Naan", price: 100, category: "Tandoor", description: "Garlic flavored naan", available: true, perishable: true, kitchenRequired: true },
  { name: "Kalwanji Naan", price: 100, category: "Tandoor", description: "Kalwanji seeds naan", available: true, perishable: true, kitchenRequired: true },
  { name: "Ginger Naan", price: 100, category: "Tandoor", description: "Ginger flavored naan", available: true, perishable: true, kitchenRequired: true },
  { name: "Plain Naan", price: 25, category: "Tandoor", description: "Plain tandoori naan", available: true, perishable: true, kitchenRequired: true },
  { name: "Tandoori Pratha", price: 110, category: "Tandoor", description: "Crispy tandoori paratha", available: true, perishable: true, kitchenRequired: true },
  { name: "Tandoori Roti", price: 20, category: "Tandoor", description: "Tandoor-baked roti", available: true, perishable: true, kitchenRequired: true },
  { name: "Naan Basket", price: 400, category: "Tandoor", description: "Assorted naan basket", available: true, perishable: true, kitchenRequired: true },
  { name: "Deal-1 (Kabli Pulao + Steam Roast)", price: 1200, category: "Deals", description: "Half Kabli Pulao, Half Steam Roast, 1 NR Drink, Mint Sauce", available: true, perishable: true, kitchenRequired: true },
  { name: "Deal-2 (Egg Rice + Manchurian)", price: 1100, category: "Deals", description: "Half Egg Rice, Half Manchurian/Chili Dry, 1 NR Drink", available: true, perishable: true, kitchenRequired: true },
  { name: "Deal-3 (Kabli + Kababs)", price: 1000, category: "Deals", description: "Half Kabli Pulao, 1 PC Chicken Kabab, 1 PC Beef Kabab, Drink", available: true, perishable: true, kitchenRequired: true },
  { name: "Deal-4 (Kabli + Reshmi)", price: 1000, category: "Deals", description: "Half Kabli Pulao, 2 PC Reshmi Kabab, Drink, Mint Sauce", available: true, perishable: true, kitchenRequired: true },
  { name: "Deal-5 (Kabli + Tikka)", price: 800, category: "Deals", description: "Half Kabli Pulao, Chicken Tikka, Drink, Mint Sauce", available: true, perishable: true, kitchenRequired: true },
  { name: "Deal-6 (Karahi/Handi)", price: 650, category: "Deals", description: "1/4 Chicken Karahi/Handi, 1 Roghni Naan, Drink, Raita", available: true, perishable: true, kitchenRequired: true },
  { name: "Deal-7 (Kabli + Shami)", price: 700, category: "Deals", description: "Half Kabli Pulao, 2 PC Shami Kabab, Drink, Mint Sauce", available: true, perishable: true, kitchenRequired: true },
  { name: "Mutton Platter (Full)", price: 8500, category: "Platters", description: "Full mutton platter with BBQ, Kabli Pulao, Naan, Drink", available: true, perishable: true, kitchenRequired: true },
  { name: "Mutton Platter (Half)", price: 4200, category: "Platters", description: "Half mutton platter", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Platter (Full)", price: 6800, category: "Platters", description: "Full chicken platter with steam roast, BBQ, Kabli Pulao", available: true, perishable: true, kitchenRequired: true },
  { name: "Chicken Platter (Half)", price: 3300, category: "Platters", description: "Half chicken platter", available: true, perishable: true, kitchenRequired: true },
  { name: "BBQ Platter (Full)", price: 6500, category: "Platters", description: "Full BBQ platter with assorted kababs, Kabli Pulao", available: true, perishable: true, kitchenRequired: true },
  { name: "BBQ Platter (Half)", price: 3300, category: "Platters", description: "Half BBQ platter", available: true, perishable: true, kitchenRequired: true },
  { name: "Fresh Mint Margarita", price: 250, category: "Beverages", description: "Refreshing mint margarita", available: true, perishable: true, kitchenRequired: false },
  { name: "Lemonade", price: 250, category: "Beverages", description: "Fresh lemonade", available: true, perishable: true, kitchenRequired: false },
  { name: "Fresh Lime", price: 200, category: "Beverages", description: "Fresh lime drink", available: true, perishable: true, kitchenRequired: false },
  { name: "Can Drink", price: 150, category: "Beverages", description: "Canned soft drink", available: true, perishable: false, kitchenRequired: false },
  { name: "Diet Can Drink", price: 160, category: "Beverages", description: "Diet canned drink", available: true, perishable: false, kitchenRequired: false },
  { name: "1.5 Liter Drink", price: 280, category: "Beverages", description: "1.5 liter soft drink", available: true, perishable: false, kitchenRequired: false },
  { name: "Mix Tea", price: 100, category: "Beverages", description: "Traditional mix tea", available: true, perishable: false, kitchenRequired: false },
  { name: "Green Tea", price: 80, category: "Beverages", description: "Green tea", available: true, perishable: false, kitchenRequired: false },
  { name: "Milk Coffee", price: 400, category: "Beverages", description: "Hot milk coffee", available: true, perishable: true, kitchenRequired: false },
  { name: "Black Coffee", price: 300, category: "Beverages", description: "Black coffee", available: true, perishable: true, kitchenRequired: false },
  { name: "Mineral Water (Large)", price: 120, category: "Beverages", description: "Large mineral water", available: true, perishable: false, kitchenRequired: false },
  { name: "Mineral Water (Small)", price: 100, category: "Beverages", description: "Small mineral water", available: true, perishable: false, kitchenRequired: false },
  { name: "Lassi Mango", price: 300, category: "Beverages", description: "Mango flavored lassi", available: true, perishable: true, kitchenRequired: false },
  { name: "Lassi Sweet", price: 200, category: "Beverages", description: "Sweet lassi", available: true, perishable: true, kitchenRequired: false },
  { name: "Lassi Saltish", price: 200, category: "Beverages", description: "Salty lassi", available: true, perishable: true, kitchenRequired: false },
  { name: "Shake (Small)", price: 120, category: "Beverages", description: "Small milkshake", available: true, perishable: true, kitchenRequired: false },
  { name: "Shake (Large)", price: 200, category: "Beverages", description: "Large milkshake", available: true, perishable: true, kitchenRequired: false },
  { name: "Kheer", price: 200, category: "Desserts", description: "Traditional rice kheer", available: true, perishable: true, kitchenRequired: false },
  { name: "Gajar Halwa", price: 350, category: "Desserts", description: "Carrot halwa dessert", available: true, perishable: true, kitchenRequired: false },
  { name: "Ice Cream (Single Scoop)", price: 120, category: "Desserts", description: "Single scoop ice cream", available: true, perishable: true, kitchenRequired: false },
  { name: "Ice Cream (Double Scoop)", price: 200, category: "Desserts", description: "Double scoop ice cream", available: true, perishable: true, kitchenRequired: false },
];

module.exports = { MENU_ITEMS };