module.exports = {
  User: require("./user"),
  Permission: require("./permission"),
  MenuItem: require("./menuItem"),
  MenuCategory: require("./category"),
  Order: require("./order"),
  InventoryItem: require("./inventoryItem"),
  InventoryLog: require("./inventoryLog"),
  Supplier: require("./supplier"),
  Employee: require("./employee"),
  Attendance: require("./attendance"),
  LeaveRequest: require("./leaveRequest"),
  LeaveBalance: require("./leaveBalance"),
  SalaryRecord: require("./salaryRecord"),
  Shift: require("./shift"),
  Floor: require("./floor"),
  Table: require("./table"),
  Delivery: require("./delivery"),
  PrinterConfig: require("./printerConfig"),
  PosTabConfig: require("./posTabConfig"),
  GiftCard: require("./giftCard"),
  LoyaltyMember: require("./loyaltyMember"),
  FbrConfig: require("./fbrConfig"),
  TaxConfig: require("./taxConfig"),
  MobileConfig: require("./mobileConfig"),
  Expense: require("./expense"),
};
